package mazza

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.52

import (
	"context"
	"fmt"
	"mazza/app/manager/clients"
	"mazza/mazza/generated/model"
)

// ClientList is the resolver for the clientList field.
func (r *queryResolver) ClientList(ctx context.Context, top *int) ([]*model.ClientList, error) {
	return clients.GetClientList(ctx, r.client, top)
}

// SupplierList is the resolver for the supplierList field.
func (r *queryResolver) SupplierList(ctx context.Context, top *int) ([]*model.SupplierList, error) {
	panic(fmt.Errorf("not implemented: SupplierList - supplierList"))
}
