// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mazza/ent/cashmovement"
	"mazza/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CashMovementDelete is the builder for deleting a CashMovement entity.
type CashMovementDelete struct {
	config
	hooks    []Hook
	mutation *CashMovementMutation
}

// Where appends a list predicates to the CashMovementDelete builder.
func (cmd *CashMovementDelete) Where(ps ...predicate.CashMovement) *CashMovementDelete {
	cmd.mutation.Where(ps...)
	return cmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cmd *CashMovementDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cmd.sqlExec, cmd.mutation, cmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cmd *CashMovementDelete) ExecX(ctx context.Context) int {
	n, err := cmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cmd *CashMovementDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cashmovement.Table, sqlgraph.NewFieldSpec(cashmovement.FieldID, field.TypeInt))
	if ps := cmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cmd.mutation.done = true
	return affected, err
}

// CashMovementDeleteOne is the builder for deleting a single CashMovement entity.
type CashMovementDeleteOne struct {
	cmd *CashMovementDelete
}

// Where appends a list predicates to the CashMovementDelete builder.
func (cmdo *CashMovementDeleteOne) Where(ps ...predicate.CashMovement) *CashMovementDeleteOne {
	cmdo.cmd.mutation.Where(ps...)
	return cmdo
}

// Exec executes the deletion query.
func (cmdo *CashMovementDeleteOne) Exec(ctx context.Context) error {
	n, err := cmdo.cmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cashmovement.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cmdo *CashMovementDeleteOne) ExecX(ctx context.Context) {
	if err := cmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
