// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mazza/ent/predicate"
	"mazza/ent/receivable"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReceivableDelete is the builder for deleting a Receivable entity.
type ReceivableDelete struct {
	config
	hooks    []Hook
	mutation *ReceivableMutation
}

// Where appends a list predicates to the ReceivableDelete builder.
func (rd *ReceivableDelete) Where(ps ...predicate.Receivable) *ReceivableDelete {
	rd.mutation.Where(ps...)
	return rd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rd *ReceivableDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rd.sqlExec, rd.mutation, rd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rd *ReceivableDelete) ExecX(ctx context.Context) int {
	n, err := rd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rd *ReceivableDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(receivable.Table, sqlgraph.NewFieldSpec(receivable.FieldID, field.TypeInt))
	if ps := rd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rd.mutation.done = true
	return affected, err
}

// ReceivableDeleteOne is the builder for deleting a single Receivable entity.
type ReceivableDeleteOne struct {
	rd *ReceivableDelete
}

// Where appends a list predicates to the ReceivableDelete builder.
func (rdo *ReceivableDeleteOne) Where(ps ...predicate.Receivable) *ReceivableDeleteOne {
	rdo.rd.mutation.Where(ps...)
	return rdo
}

// Exec executes the deletion query.
func (rdo *ReceivableDeleteOne) Exec(ctx context.Context) error {
	n, err := rdo.rd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{receivable.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rdo *ReceivableDeleteOne) ExecX(ctx context.Context) {
	if err := rdo.Exec(ctx); err != nil {
		panic(err)
	}
}
