// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mazza/ent/predicate"
	"mazza/ent/treasury"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TreasuryDelete is the builder for deleting a Treasury entity.
type TreasuryDelete struct {
	config
	hooks    []Hook
	mutation *TreasuryMutation
}

// Where appends a list predicates to the TreasuryDelete builder.
func (td *TreasuryDelete) Where(ps ...predicate.Treasury) *TreasuryDelete {
	td.mutation.Where(ps...)
	return td
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (td *TreasuryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, td.sqlExec, td.mutation, td.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (td *TreasuryDelete) ExecX(ctx context.Context) int {
	n, err := td.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (td *TreasuryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(treasury.Table, sqlgraph.NewFieldSpec(treasury.FieldID, field.TypeInt))
	if ps := td.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, td.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	td.mutation.done = true
	return affected, err
}

// TreasuryDeleteOne is the builder for deleting a single Treasury entity.
type TreasuryDeleteOne struct {
	td *TreasuryDelete
}

// Where appends a list predicates to the TreasuryDelete builder.
func (tdo *TreasuryDeleteOne) Where(ps ...predicate.Treasury) *TreasuryDeleteOne {
	tdo.td.mutation.Where(ps...)
	return tdo
}

// Exec executes the deletion query.
func (tdo *TreasuryDeleteOne) Exec(ctx context.Context) error {
	n, err := tdo.td.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{treasury.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tdo *TreasuryDeleteOne) ExecX(ctx context.Context) {
	if err := tdo.Exec(ctx); err != nil {
		panic(err)
	}
}
