// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mazza/ent/predicate"
	"mazza/ent/workshift"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkshiftDelete is the builder for deleting a Workshift entity.
type WorkshiftDelete struct {
	config
	hooks    []Hook
	mutation *WorkshiftMutation
}

// Where appends a list predicates to the WorkshiftDelete builder.
func (wd *WorkshiftDelete) Where(ps ...predicate.Workshift) *WorkshiftDelete {
	wd.mutation.Where(ps...)
	return wd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wd *WorkshiftDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, wd.sqlExec, wd.mutation, wd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wd *WorkshiftDelete) ExecX(ctx context.Context) int {
	n, err := wd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wd *WorkshiftDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(workshift.Table, sqlgraph.NewFieldSpec(workshift.FieldID, field.TypeInt))
	if ps := wd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wd.mutation.done = true
	return affected, err
}

// WorkshiftDeleteOne is the builder for deleting a single Workshift entity.
type WorkshiftDeleteOne struct {
	wd *WorkshiftDelete
}

// Where appends a list predicates to the WorkshiftDelete builder.
func (wdo *WorkshiftDeleteOne) Where(ps ...predicate.Workshift) *WorkshiftDeleteOne {
	wdo.wd.mutation.Where(ps...)
	return wdo
}

// Exec executes the deletion query.
func (wdo *WorkshiftDeleteOne) Exec(ctx context.Context) error {
	n, err := wdo.wd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workshift.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wdo *WorkshiftDeleteOne) ExecX(ctx context.Context) {
	if err := wdo.Exec(ctx); err != nil {
		panic(err)
	}
}
