// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"mazza/ent/company"
	"mazza/ent/predicate"
	"mazza/ent/worktag"
	"mazza/ent/worktask"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorktagQuery is the builder for querying Worktag entities.
type WorktagQuery struct {
	config
	ctx                *QueryContext
	order              []worktag.OrderOption
	inters             []Interceptor
	predicates         []predicate.Worktag
	withCompany        *CompanyQuery
	withWorkTasks      *WorktaskQuery
	withFKs            bool
	modifiers          []func(*sql.Selector)
	loadTotal          []func(context.Context, []*Worktag) error
	withNamedWorkTasks map[string]*WorktaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorktagQuery builder.
func (wq *WorktagQuery) Where(ps ...predicate.Worktag) *WorktagQuery {
	wq.predicates = append(wq.predicates, ps...)
	return wq
}

// Limit the number of records to be returned by this query.
func (wq *WorktagQuery) Limit(limit int) *WorktagQuery {
	wq.ctx.Limit = &limit
	return wq
}

// Offset to start from.
func (wq *WorktagQuery) Offset(offset int) *WorktagQuery {
	wq.ctx.Offset = &offset
	return wq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wq *WorktagQuery) Unique(unique bool) *WorktagQuery {
	wq.ctx.Unique = &unique
	return wq
}

// Order specifies how the records should be ordered.
func (wq *WorktagQuery) Order(o ...worktag.OrderOption) *WorktagQuery {
	wq.order = append(wq.order, o...)
	return wq
}

// QueryCompany chains the current query on the "company" edge.
func (wq *WorktagQuery) QueryCompany() *CompanyQuery {
	query := (&CompanyClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(worktag.Table, worktag.FieldID, selector),
			sqlgraph.To(company.Table, company.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, worktag.CompanyTable, worktag.CompanyColumn),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkTasks chains the current query on the "workTasks" edge.
func (wq *WorktagQuery) QueryWorkTasks() *WorktaskQuery {
	query := (&WorktaskClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(worktag.Table, worktag.FieldID, selector),
			sqlgraph.To(worktask.Table, worktask.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, worktag.WorkTasksTable, worktag.WorkTasksPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Worktag entity from the query.
// Returns a *NotFoundError when no Worktag was found.
func (wq *WorktagQuery) First(ctx context.Context) (*Worktag, error) {
	nodes, err := wq.Limit(1).All(setContextOp(ctx, wq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{worktag.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wq *WorktagQuery) FirstX(ctx context.Context) *Worktag {
	node, err := wq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Worktag ID from the query.
// Returns a *NotFoundError when no Worktag ID was found.
func (wq *WorktagQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wq.Limit(1).IDs(setContextOp(ctx, wq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{worktag.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wq *WorktagQuery) FirstIDX(ctx context.Context) int {
	id, err := wq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Worktag entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Worktag entity is found.
// Returns a *NotFoundError when no Worktag entities are found.
func (wq *WorktagQuery) Only(ctx context.Context) (*Worktag, error) {
	nodes, err := wq.Limit(2).All(setContextOp(ctx, wq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{worktag.Label}
	default:
		return nil, &NotSingularError{worktag.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wq *WorktagQuery) OnlyX(ctx context.Context) *Worktag {
	node, err := wq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Worktag ID in the query.
// Returns a *NotSingularError when more than one Worktag ID is found.
// Returns a *NotFoundError when no entities are found.
func (wq *WorktagQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wq.Limit(2).IDs(setContextOp(ctx, wq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{worktag.Label}
	default:
		err = &NotSingularError{worktag.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wq *WorktagQuery) OnlyIDX(ctx context.Context) int {
	id, err := wq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Worktags.
func (wq *WorktagQuery) All(ctx context.Context) ([]*Worktag, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryAll)
	if err := wq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Worktag, *WorktagQuery]()
	return withInterceptors[[]*Worktag](ctx, wq, qr, wq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wq *WorktagQuery) AllX(ctx context.Context) []*Worktag {
	nodes, err := wq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Worktag IDs.
func (wq *WorktagQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wq.ctx.Unique == nil && wq.path != nil {
		wq.Unique(true)
	}
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryIDs)
	if err = wq.Select(worktag.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wq *WorktagQuery) IDsX(ctx context.Context) []int {
	ids, err := wq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wq *WorktagQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryCount)
	if err := wq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wq, querierCount[*WorktagQuery](), wq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wq *WorktagQuery) CountX(ctx context.Context) int {
	count, err := wq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wq *WorktagQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryExist)
	switch _, err := wq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wq *WorktagQuery) ExistX(ctx context.Context) bool {
	exist, err := wq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorktagQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wq *WorktagQuery) Clone() *WorktagQuery {
	if wq == nil {
		return nil
	}
	return &WorktagQuery{
		config:        wq.config,
		ctx:           wq.ctx.Clone(),
		order:         append([]worktag.OrderOption{}, wq.order...),
		inters:        append([]Interceptor{}, wq.inters...),
		predicates:    append([]predicate.Worktag{}, wq.predicates...),
		withCompany:   wq.withCompany.Clone(),
		withWorkTasks: wq.withWorkTasks.Clone(),
		// clone intermediate query.
		sql:  wq.sql.Clone(),
		path: wq.path,
	}
}

// WithCompany tells the query-builder to eager-load the nodes that are connected to
// the "company" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WorktagQuery) WithCompany(opts ...func(*CompanyQuery)) *WorktagQuery {
	query := (&CompanyClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withCompany = query
	return wq
}

// WithWorkTasks tells the query-builder to eager-load the nodes that are connected to
// the "workTasks" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WorktagQuery) WithWorkTasks(opts ...func(*WorktaskQuery)) *WorktagQuery {
	query := (&WorktaskClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withWorkTasks = query
	return wq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Worktag.Query().
//		GroupBy(worktag.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wq *WorktagQuery) GroupBy(field string, fields ...string) *WorktagGroupBy {
	wq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorktagGroupBy{build: wq}
	grbuild.flds = &wq.ctx.Fields
	grbuild.label = worktag.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt,omitempty"`
//	}
//
//	client.Worktag.Query().
//		Select(worktag.FieldCreatedAt).
//		Scan(ctx, &v)
func (wq *WorktagQuery) Select(fields ...string) *WorktagSelect {
	wq.ctx.Fields = append(wq.ctx.Fields, fields...)
	sbuild := &WorktagSelect{WorktagQuery: wq}
	sbuild.label = worktag.Label
	sbuild.flds, sbuild.scan = &wq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorktagSelect configured with the given aggregations.
func (wq *WorktagQuery) Aggregate(fns ...AggregateFunc) *WorktagSelect {
	return wq.Select().Aggregate(fns...)
}

func (wq *WorktagQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wq); err != nil {
				return err
			}
		}
	}
	for _, f := range wq.ctx.Fields {
		if !worktag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wq.path != nil {
		prev, err := wq.path(ctx)
		if err != nil {
			return err
		}
		wq.sql = prev
	}
	return nil
}

func (wq *WorktagQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Worktag, error) {
	var (
		nodes       = []*Worktag{}
		withFKs     = wq.withFKs
		_spec       = wq.querySpec()
		loadedTypes = [2]bool{
			wq.withCompany != nil,
			wq.withWorkTasks != nil,
		}
	)
	if wq.withCompany != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, worktag.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Worktag).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Worktag{config: wq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(wq.modifiers) > 0 {
		_spec.Modifiers = wq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wq.withCompany; query != nil {
		if err := wq.loadCompany(ctx, query, nodes, nil,
			func(n *Worktag, e *Company) { n.Edges.Company = e }); err != nil {
			return nil, err
		}
	}
	if query := wq.withWorkTasks; query != nil {
		if err := wq.loadWorkTasks(ctx, query, nodes,
			func(n *Worktag) { n.Edges.WorkTasks = []*Worktask{} },
			func(n *Worktag, e *Worktask) { n.Edges.WorkTasks = append(n.Edges.WorkTasks, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range wq.withNamedWorkTasks {
		if err := wq.loadWorkTasks(ctx, query, nodes,
			func(n *Worktag) { n.appendNamedWorkTasks(name) },
			func(n *Worktag, e *Worktask) { n.appendNamedWorkTasks(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range wq.loadTotal {
		if err := wq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wq *WorktagQuery) loadCompany(ctx context.Context, query *CompanyQuery, nodes []*Worktag, init func(*Worktag), assign func(*Worktag, *Company)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Worktag)
	for i := range nodes {
		if nodes[i].company_work_tags == nil {
			continue
		}
		fk := *nodes[i].company_work_tags
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(company.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "company_work_tags" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (wq *WorktagQuery) loadWorkTasks(ctx context.Context, query *WorktaskQuery, nodes []*Worktag, init func(*Worktag), assign func(*Worktag, *Worktask)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Worktag)
	nids := make(map[int]map[*Worktag]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(worktag.WorkTasksTable)
		s.Join(joinT).On(s.C(worktask.FieldID), joinT.C(worktag.WorkTasksPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(worktag.WorkTasksPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(worktag.WorkTasksPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Worktag]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Worktask](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "workTasks" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (wq *WorktagQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wq.querySpec()
	if len(wq.modifiers) > 0 {
		_spec.Modifiers = wq.modifiers
	}
	_spec.Node.Columns = wq.ctx.Fields
	if len(wq.ctx.Fields) > 0 {
		_spec.Unique = wq.ctx.Unique != nil && *wq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wq.driver, _spec)
}

func (wq *WorktagQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(worktag.Table, worktag.Columns, sqlgraph.NewFieldSpec(worktag.FieldID, field.TypeInt))
	_spec.From = wq.sql
	if unique := wq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wq.path != nil {
		_spec.Unique = true
	}
	if fields := wq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, worktag.FieldID)
		for i := range fields {
			if fields[i] != worktag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wq *WorktagQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wq.driver.Dialect())
	t1 := builder.Table(worktag.Table)
	columns := wq.ctx.Fields
	if len(columns) == 0 {
		columns = worktag.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wq.sql != nil {
		selector = wq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wq.ctx.Unique != nil && *wq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wq.predicates {
		p(selector)
	}
	for _, p := range wq.order {
		p(selector)
	}
	if offset := wq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedWorkTasks tells the query-builder to eager-load the nodes that are connected to the "workTasks"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (wq *WorktagQuery) WithNamedWorkTasks(name string, opts ...func(*WorktaskQuery)) *WorktagQuery {
	query := (&WorktaskClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if wq.withNamedWorkTasks == nil {
		wq.withNamedWorkTasks = make(map[string]*WorktaskQuery)
	}
	wq.withNamedWorkTasks[name] = query
	return wq
}

// WorktagGroupBy is the group-by builder for Worktag entities.
type WorktagGroupBy struct {
	selector
	build *WorktagQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wgb *WorktagGroupBy) Aggregate(fns ...AggregateFunc) *WorktagGroupBy {
	wgb.fns = append(wgb.fns, fns...)
	return wgb
}

// Scan applies the selector query and scans the result into the given value.
func (wgb *WorktagGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wgb.build.ctx, ent.OpQueryGroupBy)
	if err := wgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorktagQuery, *WorktagGroupBy](ctx, wgb.build, wgb, wgb.build.inters, v)
}

func (wgb *WorktagGroupBy) sqlScan(ctx context.Context, root *WorktagQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wgb.fns))
	for _, fn := range wgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wgb.flds)+len(wgb.fns))
		for _, f := range *wgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorktagSelect is the builder for selecting fields of Worktag entities.
type WorktagSelect struct {
	*WorktagQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ws *WorktagSelect) Aggregate(fns ...AggregateFunc) *WorktagSelect {
	ws.fns = append(ws.fns, fns...)
	return ws
}

// Scan applies the selector query and scans the result into the given value.
func (ws *WorktagSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ws.ctx, ent.OpQuerySelect)
	if err := ws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorktagQuery, *WorktagSelect](ctx, ws.WorktagQuery, ws, ws.inters, v)
}

func (ws *WorktagSelect) sqlScan(ctx context.Context, root *WorktagQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ws.fns))
	for _, fn := range ws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
